[tool.poetry]
name = "meine-stadt-transparent"
version = "0.2.0"
description = "A website to bring municipal politics to citizens"
authors = ["Tobias Hößl <tobias@hoessl.eu>", "Konstantin Schütze <konstin@mailbox.org>"]
license = "MIT"

[tool.poetry.dependencies]
Django = "~2.1"
django-allauth = "^0.39"
django-anymail = "^6.0"
django-braces = "^1.13"
django_csp = "^3.4"
django-elasticsearch-dsl = "~6.4.2"
django-environ = "^0.4"
django-geojson = "^2.12"
django-settings-export = "^1.2"
django-simple-history = "^2.3"
django-webpack-loader = "^0.6"
django-widget-tweaks = "^1.4"
elasticsearch-dsl = "~6.4.0"
geoextract = "^0.3.1"
geopy = "^1.20"
gunicorn = "^19.9"
html2text = "^2019.8"
icalendar = "^4.0"
jsonfield = "^2.0"
mysqlclient = "^1.3"
pgpy = { version = "^0.4.3", optional = true }
PyPDF2 = "^1.26"
python = "^3.6"
python-slugify = "^3.0"
requests = "^2.22"
splinter = "^0.11"
Wand = "^0.5.7"
sentry-sdk = "^0.11.2"
minio = "^5.0"
tqdm = "^4.29"
python-dateutil = "^2.7"
wagtail = "~2.6"
django-decorator-include = "^2.1"
dataclasses = { version = "^0.6.0", optional = true }
cattrs = { git = "https://github.com/Tinche/cattrs", rev = "7311176e15970cba50c7c435a4e6e353c00bfeaf", optional = true }


[tool.poetry.dev-dependencies]
selenium = "3.141.0"
tox = "^3.13"
django-debug-toolbar = "^2.0"
responses = "^0.10.6"
pytest-django = "^3.5"
black = "19.3b0"

[tool.poetry.extras]
pgp = ["pgpy"]
import-json = ["dataclasses", "cattrs"]

[tool.black]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | \.tox
  | mainapp/migrations
  | cms/migrations
  | importer/migrations
  | node_modules
  | static
)/
'''

[build-system]
requires = ["poetry >= 0.12, <1"]
build-backend = "poetry.masonry.api"
